# Generated by Django 3.2.6 on 2021-08-22 08:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to='')),
                ('description', models.TextField(default='Description')),
                ('state', models.ForeignKey(default='OPEN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.state')),
                ('userId', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
