# Generated by Django 3.2.6 on 2021-08-22 08:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(default='Description')),
                ('progression', models.IntegerField(default='0')),
                ('project_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.project')),
                ('state', models.ForeignKey(default='OPEN', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.state')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.type')),
            ],
        ),
    ]
