# Generated by Django 3.2.6 on 2021-09-12 21:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20210904_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='userId',
            field=models.ManyToManyField(related_name='user_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
