# Generated by Django 3.2.6 on 2021-10-03 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_commenttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complete_per',
            field=models.FloatField(default=60, max_length=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
