# Generated by Django 3.2.6 on 2021-10-04 19:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211003_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='complete_per',
            field=models.FloatField(default=0, max_length=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
